add document on how to join using state sync
bandprotocol/launch pull request #58
Opened 2022-10-27 04:52 UTC by colmazia

Only State Sync doc for to generate a link to use in readme.md

2022-10-27 15:28 UTC, RogerKSI requested changes

2022-10-27 15:28 UTC, RogerKSI commented on band-laozi-testnet6/docs/how-to-join-as-a-validator-using-statesync.md
> +# Clone Bandchain Laozi version v2.3.6
2.4.0

2022-10-27 15:28 UTC, RogerKSI commented on band-laozi-testnet6/docs/how-to-join-as-a-validator-using-statesync.md
> +
remove space and line

2022-10-27 15:28 UTC, RogerKSI commented on band-laozi-testnet6/docs/how-to-join-as-a-validator-using-statesync.md
> +Then, check Yoda version that we have compiled. It should be `v2.3.6`.
2.4.0

2022-10-31 04:33 UTC, RogerKSI approved these changes

2022-11-01 05:34 UTC, RogerKSI approved these changes

2022-11-01 05:59 UTC, satawatnack approved these changes

2022-11-01 07:44 UTC, merged