update readme to be testnet6 version
bandprotocol/launch pull request #59
Opened 2022-11-01 07:49 UTC by colmazia

2022-11-01 19:20 UTC, RogerKSI approved these changes

2022-11-02 07:00 UTC, satawatnack requested changes

2022-11-02 07:00 UTC, satawatnack commented on band-laozi-testnet6/README.md
> +This document describes methods on how to join as a validator in Laozi testnet #6 without using State Sync. If you want to join using State Sync please follow this document https://github.com/bandpro
`[url](url)` can change to link

2022-11-03 07:22 UTC, colmazia commented on band-laozi-testnet6/README.md
> +This document describes methods on how to join as a validator in Laozi testnet #6 without using State Sync. If you want to join using State Sync please follow this document https://github.com/bandpro
done

2022-11-03 07:27 UTC, satawatnack approved these changes

2022-11-03 07:58 UTC, merged