remove RPC_ENDPOINT var
bandprotocol/launch pull request #64
Opened 2022-11-16 07:30 UTC by colmazia

2022-11-16 07:31 UTC, RogerKSI approved these changes

2022-11-17 08:46 UTC, taobun requested changes

2022-11-17 08:46 UTC, taobun commented on band-laozi-testnet6/docs/how-to-join-as-a-validator-using-statesync.md
> +LATEST_HEIGHT=$(curl -s https://rpc.laozi-testnet6.bandchain.org:443/block | jq -r .result.block.header.height);
Remove 443 please

2022-11-23 08:38 UTC, taobun approved these changes

2022-11-23 08:38 UTC, merged